import Head from "next/head";
import { Box } from "@chakra-ui/react";
import { QuestionCard } from "../components/QuestionCard";
import { useAbi } from "../hooks/useAbi";
import { useContractRead } from "wagmi";

export default function Home() {
  const abi = useAbi();
  const { data, isLoading } = useContractRead({
    addressOrName: process.env.NEXT_PUBLIC_CONTRACT_ADDRESS,
    contractInterface: abi,
    functionName: "getLatestQuestion",
    args: [1],
  });
  return (
    <>
      <Head>
        <title>Kue 3</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box py={32} w={"100%"} px={16}>
        {isLoading ? (
          <Box>Loading...</Box>
        ) : data ? (
          data.map((eachQue) => {
            return (
              <Box key={eachQue.id.toString()} mb={8} maxW={"60%"} marginX="auto">
                <QuestionCard question={eachQue} />
              </Box>
            );
          })
        ) : null}
      </Box>
    </>
  );
}
