import Head from "next/head";
import { Box } from "@chakra-ui/react";
import { QuestionCard } from "../components/QuestionCard";
import { useAbi } from "../hooks/useAbi";
import { readContract } from "@wagmi/core";
import { useEffect, useState } from "react";

export default function Home() {
  const abi = useAbi();
  const [data, setData] = useState([]);

  useEffect(() => {
    readContract({
      address: process.env.NEXT_PUBLIC_CONTRACT_ADDRESS,
      abi: abi,
      functionName: "getLatestQuestion",
      args: [1],
    }).then((res) => {
      setData(res);
    });
  }, []);
  return (
    <>
      <Head>
        <title>Kue 3</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box py={32} w={"100%"} px={16}>
        {!data ? (
          <Box>Loading...</Box>
        ) : data ? (
          data.map((eachQue) => {
            return (
              <Box key={eachQue.id.toString()} mb={8} maxW={"60%"} marginX="auto">
                <QuestionCard question={eachQue} />
              </Box>
            );
          })
        ) : (
          "No questions asked yet"
        )}
      </Box>
    </>
  );
}
